/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UploadImport } from './routes/upload'
import { Route as SimulatorImport } from './routes/simulator'
import { Route as ProfileImport } from './routes/profile'
import { Route as CommandImport } from './routes/command'
import { Route as ArchetypesImport } from './routes/archetypes'
import { Route as IndexImport } from './routes/index'
import { Route as AnalysisConversationIdImport } from './routes/analysis.$conversationId'

// Create/Update Routes

const UploadRoute = UploadImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRoute,
} as any)

const SimulatorRoute = SimulatorImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const CommandRoute = CommandImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRoute,
} as any)

const ArchetypesRoute = ArchetypesImport.update({
  id: '/archetypes',
  path: '/archetypes',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AnalysisConversationIdRoute = AnalysisConversationIdImport.update({
  id: '/analysis/$conversationId',
  path: '/analysis/$conversationId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/archetypes': {
      id: '/archetypes'
      path: '/archetypes'
      fullPath: '/archetypes'
      preLoaderRoute: typeof ArchetypesImport
      parentRoute: typeof rootRoute
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorImport
      parentRoute: typeof rootRoute
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadImport
      parentRoute: typeof rootRoute
    }
    '/analysis/$conversationId': {
      id: '/analysis/$conversationId'
      path: '/analysis/$conversationId'
      fullPath: '/analysis/$conversationId'
      preLoaderRoute: typeof AnalysisConversationIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archetypes': typeof ArchetypesRoute
  '/command': typeof CommandRoute
  '/profile': typeof ProfileRoute
  '/simulator': typeof SimulatorRoute
  '/upload': typeof UploadRoute
  '/analysis/$conversationId': typeof AnalysisConversationIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archetypes': typeof ArchetypesRoute
  '/command': typeof CommandRoute
  '/profile': typeof ProfileRoute
  '/simulator': typeof SimulatorRoute
  '/upload': typeof UploadRoute
  '/analysis/$conversationId': typeof AnalysisConversationIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/archetypes': typeof ArchetypesRoute
  '/command': typeof CommandRoute
  '/profile': typeof ProfileRoute
  '/simulator': typeof SimulatorRoute
  '/upload': typeof UploadRoute
  '/analysis/$conversationId': typeof AnalysisConversationIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archetypes'
    | '/command'
    | '/profile'
    | '/simulator'
    | '/upload'
    | '/analysis/$conversationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archetypes'
    | '/command'
    | '/profile'
    | '/simulator'
    | '/upload'
    | '/analysis/$conversationId'
  id:
    | '__root__'
    | '/'
    | '/archetypes'
    | '/command'
    | '/profile'
    | '/simulator'
    | '/upload'
    | '/analysis/$conversationId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchetypesRoute: typeof ArchetypesRoute
  CommandRoute: typeof CommandRoute
  ProfileRoute: typeof ProfileRoute
  SimulatorRoute: typeof SimulatorRoute
  UploadRoute: typeof UploadRoute
  AnalysisConversationIdRoute: typeof AnalysisConversationIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchetypesRoute: ArchetypesRoute,
  CommandRoute: CommandRoute,
  ProfileRoute: ProfileRoute,
  SimulatorRoute: SimulatorRoute,
  UploadRoute: UploadRoute,
  AnalysisConversationIdRoute: AnalysisConversationIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/archetypes",
        "/command",
        "/profile",
        "/simulator",
        "/upload",
        "/analysis/$conversationId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/archetypes": {
      "filePath": "archetypes.tsx"
    },
    "/command": {
      "filePath": "command.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/simulator": {
      "filePath": "simulator.tsx"
    },
    "/upload": {
      "filePath": "upload.tsx"
    },
    "/analysis/$conversationId": {
      "filePath": "analysis.$conversationId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
